Update client.php
WemXPro/languages pull request #15
Opened 2023-12-29 20:53 UTC by faceliftben

New Translation for the German Languages

2023-12-31 16:36 UTC, PadowYT2 commented on de/client.php
> +//Translated by Ben Kliver | faceliftben on behalf of game-paradise for wemx.com 🌐📝
Please do not these comments

2023-12-31 16:37 UTC, PadowYT2 requested changes
Also the file must be 4-space width, not 2

2023-12-31 16:37 UTC, PadowYT2 commented on de/client.php
> +  'more' => 'Mehr',
This shouldn't be in WemX itself

2023-12-31 16:37 UTC, PadowYT2 commented on de/client.php
> +  'excl' => 'Exkl.',
Is this used?

2024-01-01 10:52 UTC, faceliftben commented on de/client.php
> +  'excl' => 'Exkl.',
f you have installed the portal, yes

2024-01-02 22:27 UTC, PadowYT2 commented on de/client.php
> +  'excl' => 'Exkl.',
About the VAT*

2024-01-26 19:32 UTC, closed without merging